export default [
   {
      login: "ThaELL1",
      id: 37319124,
      node_id: "MDQ6VXNlcjM3MzE5MTI0",
      avatar_url: "https://avatars3.githubusercontent.com/u/37319124?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ThaELL1",
      html_url: "https://github.com/ThaELL1",
      followers_url: "https://api.github.com/users/ThaELL1/followers",
      following_url: "https://api.github.com/users/ThaELL1/following{/other_user}",
      gists_url: "https://api.github.com/users/ThaELL1/gists{/gist_id}",
      starred_url: "https://api.github.com/users/ThaELL1/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ThaELL1/subscriptions",
      organizations_url: "https://api.github.com/users/ThaELL1/orgs",
      repos_url: "https://api.github.com/users/ThaELL1/repos",
      events_url: "https://api.github.com/users/ThaELL1/events{/privacy}",
      received_events_url: "https://api.github.com/users/ThaELL1/received_events",
      type: "User",
      site_admin: false,
   },
   {
      login: "MohamedWSalah",
      id: 47085535,
      node_id: "MDQ6VXNlcjQ3MDg1NTM1",
      avatar_url: "https://avatars.githubusercontent.com/u/47085535?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/MohamedWSalah",
      html_url: "https://github.com/MohamedWSalah",
      followers_url: "https://api.github.com/users/MohamedWSalah/followers",
      following_url: "https://api.github.com/users/MohamedWSalah/following{/other_user}",
      gists_url: "https://api.github.com/users/MohamedWSalah/gists{/gist_id}",
      starred_url: "https://api.github.com/users/MohamedWSalah/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/MohamedWSalah/subscriptions",
      organizations_url: "https://api.github.com/users/MohamedWSalah/orgs",
      repos_url: "https://api.github.com/users/MohamedWSalah/repos",
      events_url: "https://api.github.com/users/MohamedWSalah/events{/privacy}",
      received_events_url: "https://api.github.com/users/MohamedWSalah/received_events",
      type: "User",
      site_admin: false,
   },
];
